version: '2'
services:
  dev-sample-golang-grpc-microservice:
    image: minixxie/golang:1.7
    container_name: dev-sample-golang-grpc-microservice
    hostname: dev-sample-golang-grpc-microservice
    volumes:
      - ".:/go/src/app"
    working_dir: /go/src/app
    command: ./docker-entry.sh
    ports:
      - "8081:80"
    networks:
      - dev-backend
      - mongo_default
    environment:
      - ENV=dev
networks:
  dev-backend:
    external:
      name: dev-backend
  mongo_default:
    external:
      name: mongo_default
