version: '2'
services:
  sample-golang-grpc-microservice:
    image: minixxie/golang:1.7
    container_name: sample-golang-grpc-microservice
    hostname: sample-golang-grpc-microservice
    volumes:
      - ".:/go/src/app"
    working_dir: /go/src/app
    command: ./entry.sh
    ports:
      - "8080:80"
    networks:
      - ldev-backend
      - mongo_default
    environment:
      - MONGO_URI=${MONGO_URI}
networks:
  ldev-backend:
    external:
      name: ldev-backend
  mongo_default:
    external:
      name: mongo_default
